server:
  port: 8100

zuul:
  routes:
    doctors-service:
      url: http://localhost:8082
    patient-service:
      url: http://localhost:8083
    disease-service:
      url: http://localhost:8081
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 5000


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
